/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tallergui;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

/**
 *
 * @author James Josue Molina
 */
public class Arbol extends javax.swing.JFrame {

    /**
     * Creates new form Arbol
     */
    public Arbol() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pm_menu = new javax.swing.JPopupMenu();
        mi_editar = new javax.swing.JMenuItem();
        jScrollPane1 = new javax.swing.JScrollPane();
        jt_directorio = new javax.swing.JTree();
        btn_directorio = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        tb_nombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tb_contenido = new javax.swing.JTextArea();
        btn_subir = new javax.swing.JButton();
        btn_editar = new javax.swing.JButton();

        mi_editar.setText("Editar");
        mi_editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mi_editarActionPerformed(evt);
            }
        });
        pm_menu.add(mi_editar);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Z:/");
        jt_directorio.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jt_directorio.setComponentPopupMenu(pm_menu);
        jScrollPane1.setViewportView(jt_directorio);

        btn_directorio.setText("Directorio");
        btn_directorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_directorioActionPerformed(evt);
            }
        });

        jLabel1.setText("Nombre");

        jLabel2.setText("Contenido");

        tb_contenido.setColumns(20);
        tb_contenido.setRows(5);
        jScrollPane2.setViewportView(tb_contenido);

        btn_subir.setText("Subir");
        btn_subir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_subirActionPerformed(evt);
            }
        });

        btn_editar.setText("Editar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addComponent(btn_directorio, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1)
                    .addComponent(tb_nombre)
                    .addComponent(jLabel2)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_subir, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_editar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(139, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(btn_directorio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tb_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_subir)
                            .addComponent(btn_editar))))
                .addContainerGap(120, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_directorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_directorioActionPerformed
        //FALTA ARREGLAR ALGUNOS CASOS
        JFileChooser directory = new JFileChooser();
        directory.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        int valor = directory.showSaveDialog(null);
        if(valor == JFileChooser.APPROVE_OPTION){
            String path = directory.getSelectedFile().getPath();
            DefaultTreeModel modelo = (DefaultTreeModel)jt_directorio.getModel();
            DefaultMutableTreeNode root = (DefaultMutableTreeNode)modelo.getRoot();
            direccion = path;
            root.removeAllChildren();
            llenarArbol(path, root);
            modelo.reload();
        }
        
    }//GEN-LAST:event_btn_directorioActionPerformed

    private void btn_subirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_subirActionPerformed
        String pathTemp = jt_directorio.getSelectionPath().toString();
        pathTemp = pathTemp.substring(1, pathTemp.length() -1 );
        String[] directorioAux = pathTemp.split(",");
        String path = "";
        for (int i = 0; i < directorioAux.length; i++)
            if(i != 0)
                path += directorioAux[i].replace(" ", "") + "\\";
        
        try{
            path += tb_nombre.getText() + ".txt";
            BufferedWriter bw = new BufferedWriter(new FileWriter(direccion + "/" + path,true));
            bw.write(tb_contenido.getText() + "\n");
            bw.close();
        }catch(Exception ex){
            System.out.println(ex);
        }
        DefaultTreeModel modelo = (DefaultTreeModel)jt_directorio.getModel();
        DefaultMutableTreeNode root = (DefaultMutableTreeNode)modelo.getRoot();
        root.removeAllChildren();
        llenarArbol(direccion, root);
        modelo.reload();
        
        JOptionPane.showMessageDialog(null,"Creado exitosamente!");
        tb_contenido.setText("");
        tb_nombre.setText("");
    }//GEN-LAST:event_btn_subirActionPerformed

    private void mi_editarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mi_editarActionPerformed
        String pathTemp = jt_directorio.getSelectionPath().toString();
        pathTemp = pathTemp.substring(1, pathTemp.length() -1 );
        String[] directorioAux = pathTemp.split(",");
        String path = "";
        String fileName = "";
        for (int i = 0; i < directorioAux.length; i++){
            if(i != 0)
                path += directorioAux[i].replace(" ", "") + "\\";
            if(i == directorioAux.length - 1)
                fileName = directorioAux[i].replace(" ", "");
        }
        try{
            BufferedReader br = new BufferedReader(new FileReader(direccion + "/" + path));
            String linea = "";
            while( (linea = br.readLine()) != null)
                tb_contenido.append(linea); //Metodo append agrega lineas sin borrar las anteriores
            tb_nombre.setText(fileName);
        }catch(Exception ex){
            System.out.println(ex);
        }
       
    }//GEN-LAST:event_mi_editarActionPerformed

    private DefaultMutableTreeNode llenarArbol(String path, DefaultMutableTreeNode padre){
        String[] lista = (new File(path)).list();
        if(lista != null && lista.length > 0)
            for (String string : lista)
                padre.add( llenarArbol(path + "\\" + string, new DefaultMutableTreeNode(string)));
        else if(lista != null)
            return new DefaultMutableTreeNode(lista[0]);
        return padre;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Arbol.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Arbol.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Arbol.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Arbol.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Arbol().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_directorio;
    private javax.swing.JButton btn_editar;
    private javax.swing.JButton btn_subir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTree jt_directorio;
    private javax.swing.JMenuItem mi_editar;
    private javax.swing.JPopupMenu pm_menu;
    private javax.swing.JTextArea tb_contenido;
    private javax.swing.JTextField tb_nombre;
    // End of variables declaration//GEN-END:variables
    private String direccion;
}
